package com.shuham.medilog.di

import androidx.room.Room
import androidx.sqlite.driver.bundled.BundledSQLiteDriver
import com.shuham.medilog.data.local.AppDatabase
import kotlinx.cinterop.ExperimentalForeignApi
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.IO
import org.koin.core.module.Module
import org.koin.dsl.module
import platform.Foundation.NSDocumentDirectory
import platform.Foundation.NSFileManager
import platform.Foundation.NSUserDomainMask

@OptIn(ExperimentalForeignApi::class)
actual val databaseModule: Module = module {


    single<AppDatabase> {
        // 1. Get the path to the iOS Documents directory
        val documentDirectory = NSFileManager.defaultManager.URLForDirectory(
            directory = NSDocumentDirectory,
            inDomain = NSUserDomainMask,
            appropriateForURL = null,
            create = false,
            error = null
        )

        // 2. Append the database filename
        val dbFilePath = requireNotNull(documentDirectory?.path) + "/medilog.db"

        // 3. Create the builder using the iOS specific factory
        Room.databaseBuilder<AppDatabase>(
            name = dbFilePath,
            //factory = { AppDatabase::class.instantiateImpl() } // Auto-generated by KSP
        )
            .setDriver(BundledSQLiteDriver())
            .fallbackToDestructiveMigration(true)
            .setQueryCoroutineContext(Dispatchers.IO)
            .build()
    }
}